// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesWebMvc.Models;

namespace SalesWebMvc.Migrations
{
    [DbContext(typeof(SalesWebMvcContext))]
    [Migration("20210519015049_outraMigration")]
    partial class outraMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SalesWebMvc.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("SalesWebMvc.Models.TotalVendas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int?>("StatusId");

                    b.Property<int?>("VendedorId");

                    b.Property<double>("total");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("VendedorId");

                    b.ToTable("totalVendas");
                });

            modelBuilder.Entity("SalesWebMvc.Models.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataNasc");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<double>("SalarioBase");

                    b.Property<int?>("departamentoId");

                    b.HasKey("Id");

                    b.HasIndex("departamentoId");

                    b.ToTable("vendedors");
                });

            modelBuilder.Entity("SalesWebMvc.Models.TotalVendas", b =>
                {
                    b.HasOne("SalesWebMvc.Models.TotalVendas", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.HasOne("SalesWebMvc.Models.Vendedor", "Vendedor")
                        .WithMany("vendas")
                        .HasForeignKey("VendedorId");
                });

            modelBuilder.Entity("SalesWebMvc.Models.Vendedor", b =>
                {
                    b.HasOne("SalesWebMvc.Models.Departamento", "departamento")
                        .WithMany("vendedors")
                        .HasForeignKey("departamentoId");
                });
#pragma warning restore 612, 618
        }
    }
}
